### PR TITLE
Fix examples using globs, quote * in rewrite.yml

### PR DESCRIPTION
**Pull request by fupgang**
Not quoting reserved char * in rewrite.yml results in 

```
[ERROR]  in 'reader', line 10, column 20:
[ERROR]           fileMatcher: **/application-*.yml
[ERROR]                        ^
[ERROR] unexpected character found *(42)
[ERROR]  in 'reader', line 10, column 21:
[ERROR]           fileMatcher: **/application-*.yml
[ERROR]                         ^
```

### CODE REVIEW

**Comment by fupgang** [comment]
Are the recipe docs generated from the recipe's sources?
I wonder if the following needs to be fixed instead or in addition:

```
    @Option(displayName = "File matcher",
            description = "Matching files will be renamed. This is a glob expression.",
            example = "**/application-*.yml")
    String fileMatcher;
```

Is example intended to be a valid yml value or a valid java string?

**Comment by pway99** [comment]
Hi @fupgang,  You are correct, recipe docs are autogenerated by the[recipe markdown generator]( https://github.com/openrewrite/rewrite-recipe-markdown-generator).  
Thanks so much for your help I will open an issue on that repo and we'll have a look

**Comment by pway99** [comment]
Hi @fupgang, I went ahead and fixed the recipe-markdown-generator.
Thanks again for identifying this issue and creating a PR :)

**Comment by pway99** [comment]
Re-opening, to merge these changes to help others prior to the next release

**Pull request merged**
